// swift-tools-version:5.9
// Package.swift — Swift Package Manager manifest
//
// This file is the SOURCE OF TRUTH for VoiceFlow's Swift dependencies.
// The Xcode project (generated by XcodeGen from project.yml) imports these
// via the `packages:` section in project.yml.
//
// To update dependencies:
//   1. Edit this file
//   2. Run `swift package resolve` (or open Xcode and let it sync)
//   3. Commit the changes

import PackageDescription

let package = Package(
    name: "VoiceFlow",
    platforms: [
        .iOS(.v17)
    ],
    products: [
        .library(
            name: "VoiceFlowShared",
            targets: ["VoiceFlowShared"]
        ),
    ],
    dependencies: [
        // WhisperKit — OpenAI Whisper inference via Apple Neural Engine
        // License: MIT | Argmax Inc.
        .package(
            url: "https://github.com/argmaxinc/WhisperKit",
            from: "0.7.0"
        ),
        
        // FluidAudio — Apple Silicon audio AI (Parakeet, diarization, VAD)
        // License: MIT | FluidInference
        // .package(
        //     url: "https://github.com/FluidInference/FluidAudio",
        //     from: "0.1.0"
        // ),
    ],
    targets: [
        // Shared framework — code shared between main app and keyboard extension
        .target(
            name: "VoiceFlowShared",
            dependencies: [],
            path: "Sources/VoiceFlowShared",
            swiftSettings: [
                .enableUpcomingFeature("RegionBasedIsolation"),
                .enableExperimentalFeature("StrictConcurrency"),
            ]
        ),
        
        // Tests
        .testTarget(
            name: "VoiceFlowSharedTests",
            dependencies: ["VoiceFlowShared"],
            path: "Tests/VoiceFlowSharedTests"
        ),
    ]
)
